language: go
dist: xenial
sudo: required
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd ${TRAVIS_BUILD_DIR}/tensorflow-agent/dockerfiles
  - make build
  - make push
