variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

jobs:
  - job: CPU
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: make docker_build_cpu
        workingDirectory: tensorflow-agent/dockerfiles
      - script: ./push.sh docker_push_cpu
        workingDirectory: tensorflow-agent/dockerfiles
        condition: eq(variables.isMain, true)
  - job: GPU
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: make docker_build_gpu
        workingDirectory: tensorflow-agent/dockerfiles
      - script: ./push.sh docker_push_gpu
        workingDirectory: tensorflow-agent/dockerfiles
        condition: eq(variables.isMain, true)
