jobs:
  - job: CPU
    timeoutInMinutes: 0
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd tensorflow-agent/dockerfiles
          make docker_pull_cpu
          make docker_build_cpu
          ./push.sh docker_push_cpu
  - job: GPU
    timeoutInMinutes: 0
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd tensorflow-agent/dockerfiles
          make docker_pull_gpu
          make docker_build_gpu
          ./push.sh docker_push_gpu
  - job: GPU_NGC
    timeoutInMinutes: 0
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd tensorflow-agent/dockerfiles
          make docker_pull_gpu_ngc
          make docker_build_gpu_ngc
          ./push.sh docker_push_gpu_ngc
  - job: Update_Microbadger
    dependsOn:
      - CPU
      - GPU
      - GPU_NGC
    steps:
      - script: 'curl -X POST https://hooks.microbadger.com/images/carml/tensorflow/rUwtpIDS_Lq5zy8ocJDOtZMJUf4='
