FROM c3sr/base:amd64-cpu-latest
MAINTAINER Yen-Hsiang Chang <yhchang3@illinois.edu>

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_URL
ARG VERSION
ARG ARCH
ARG FRAMEWORK_VERSION
LABEL org.carml.tensorflow.build-date=$BUILD_DATE \
      org.carml.tensorflow.name="tensorflow agent" \
      org.carml.tensorflow.description="" \
      org.carml.tensorflow.url="https://www.carml.org/" \
      org.carml.tensorflow.vcs-ref=$VCS_REF \
      org.carml.tensorflow.vcs-url=$VCS_URL \
      org.carml.tensorflow.vendor="MLModelScope" \
      org.carml.tensorflow.arch=$ARCH \
      org.carml.tensorflow.version=$VERSION \
      org.carml.tensorflow.framework_version=$FRAMEWORK_VERSION \
      org.carml.tensorflow.schema-version="1.0"

# install Tensorflow for C
RUN wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz

RUN tar -C /opt/tensorflow -xzf libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz

RUN rm libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz

# setup path
ENV CGO_CFLAGS="${CGO_CFLAGS} -I /opt/tensorflow/include"
ENV CGO_CXXFLAGS="${CGO_CXXFLAGS} -I /opt/tensorflow/include"
ENV CGO_LDFLAGS="${CGO_LDFLAGS} -L /opt/tensorflow/lib"

# get github.com/c3sr/tensorflow repository
ENV PKG github.com/c3sr/tensorflow
WORKDIR $GOPATH/src/$PKG

RUN git clone --depth=1 --branch=master https://${PKG}.git .

RUN dep ensure -v -vendor-only

RUN cd $GOPATH/src/$PKG && \
  go build -a -installsuffix cgo -ldflags "-s -w -X ${PKG}/Version=${VERSION} -X ${PKG}/GitCommit=${VCS_REF} -X ${PKG}/BuildDate=${BUILD_DATE}"&& \
  cd tensorflow-agent && \
  go install -tags=nogpu && \
  cd ..

ENTRYPOINT ["tensorflow-agent"]
